apiVersion: apps/v1
kind: Deployment
metadata:
  name: upmc
  namespace: push
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upmc
  template:
    metadata:
      labels:
        app: upmc
    spec:
      securityContext:
        fsGroup: 1000            
      containers:
        - name: upmc
          image: kimhr/upmc:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: share-volume
              mountPath: /data/share

      volumes:
        - name: share-volume
          hostPath:
            path: /kimhr/work/nas/share
            type: DirectoryOrCreate
