apiVersion: v1
kind: Service
metadata:
  name: provider-realtime-svc       
  namespace: push  
spec:
  selector:
    app: provider
    role: realtime    
  ports:
  - name: main
    port: 10420
    targetPort: 10420
  - name: ssl
    port: 18443
    targetPort: 18443
  - name: monitoring
    port: 10421
    targetPort: 10421
    

