#실시간 프로바이더 List : 구분자 쉼표
PUBLIC.PROVIDER.USE_SSL=N
PUBLIC.PROVIDER.IP=push-provider-0:10420,push-provider-1:10420
PUBLIC.PROVIDER.PORT=10420
#배치 프로바이더 List : 구분자 쉼표
PUBLIC.PROVIDER.BATCH.IP=push-provider-0:10520,push-provider-1:10520
PUBLIC.PROVIDER.BATCH.PORT=10520

## 네트웍 L4 장비를 이용하여 이중화를 하였을 경우 Y로 세팅 후 DB(T_PUSH_SERVER_GROUP, T_PUSH_SERVER_INFO) 테이블에 해당정보를 저장한다.
UPNS.GROUP_YN=N
## 그룹설정일 경우 UPNS그룹 VIP로 사용할 그룹아이디. T_PUSH_SERVER_GROUP 테이블에 있는 정보 참조.
UPNS.DEFAULT_GROUPID=
UPNS.USE_SSL=N
UPNS.MONITOR_PORT=18880
#UPNS.CUSTOM.INTERNAL_PORT=46001
#UPNS를 그룹설정을 하지 않고 L4없이 유저재분배를 하려면 해당값을 Y로 변경.
UPNS.HEALTH.CHECK_YN=N
##주의! 이중화 되어 있을경우 예약발송 메세지 발송 서버를 하나만 true로 해 준다.
RESERVEMSG.SEND=true
####이부분 부터 Daemon이 사용. 길이가 18자 이상은 안됨.
MQTT.AGENTID=UPMC_1
MAX_REQUEST_QUEUE=500000
# 보내지 못한 큐에 담긴 메세지 종료시 Disk에 저장
QUEUE.SAVE.SRC=/kimhr/work/data/upmc
# (파일큐 전용) 발송 큐의 분배 방식(기본: N / Hash 방식: Y)
QUEUE.HASH.ALGO=N

# 실시간 발송 발송요청 후 6시간이 지난 메세지 발송실패처리함.
NOTSEND_ELAPSEDTIME=6

# 주기적인 메모리 체크방식 : 발송시간 오차가 초단위로 있을 수 있으고 메모리사용량이 증가 할수 있으나 많은 건별 예약발송을 처리 할 수 있다.
RESERVE.SEND.TYPE=2
# 현재 사용하지 않음. 예약발송테이블에 CUID컬럼을 LONG, text 타입으로 만들어서 현재는 사용하지 않음.
RESERVE.FILE.SAVE=N
##DB에 저장되어 있는 예약발송 메세지 체크하는 주기(분)
RESERVEMSG.CHECK.MINUTE=1
## 발송속도가 지연되어 해당시간 이상 지났을 경우 발송 실패처리. 단윈 시간
RESERVEMSG.NOTSEND_ELAPSEDTIME=2
##예약발송 발송 처리 쓰레드 카운트
RESERVE.WORKER.COUNT=10
# 예약발송 CSV파일 저장 NAS 사용유무
NAS_USE_YN=N
# 예약발송 메세지 정보 Disk에 저장
RESERVE.SAVE.SRC=/kimhr/work/nas/share/upmc/reserve_data/
## UPMC서버가 이중화 멀티일경우 푸시발송취소, 서비스코드 동기화, 예약발송CSV파일 동기화에 사용 UPMC서버 정보를 넣어준다. 주의~!!!.자기 자신서버 아이피는 제외.
##ex)아이피:포트 : http://내부아이피1:8080/컨텍스트루트.  여러개 일경우 쉬표 구분 : http://127.0.0.2:8080/컨텍스트루트., http://127.0.0.3:8080/컨텍스트루트.
SYNC_SERVER=
SYNC_FAIL_RETRY_CNT=2
SYNC_FROM_DB_ACCEPT_DIFF_CNT=20
SYNC_FROM_DB_ATIVE_TIME=4
## 리시버가 여러대일때 어드민에서 발송 응답 할 현재리시버의 아이피url: 내부아이피 적어주세요.
## ContextRoot가 있으면 ContextRoot까지 적어주세요.마지막 /빼세요
ADMIN_RESPONSE_HOSTURL=http://127.0.0.1:8080
## 프로바이더 사용 유무(UPNS만 사용 할 경우 N)
PROVIDER_USE_YN=Y
##분할발송 파일 체크 주기
SPLIT_SENDFILE_CHECK_TIME=1

##뱃지카운트 수동:N, 자동:Y
BADGE_AUTO_YN=N

## 수동분배기능사용 여부. 기본은 AUTO이므로 N
MANUAL_ALLOCATE_YN=Y

## SMS 사용정보. SMS_USE_STORAGE 종류 1.DB . 현재는 DB밖에 없음.
SMS_USE_YN=Y
SMS_USE_STORAGE=DB

## 대량발송타입(A,M,N,C) 발송속도 조절. CPU가 과부하될 경우 아래의 시간을 늘려줌. 100 ~ 500 사이로 조정. 0은 사용하지 않음.
SEND_MILISEC_DELAY=0
######################################################################################
# 아래 설정값 문의 후 수정 하세요
######################################################################################
## 주의 확인 : UPMC 버전 업그레이드시 사용. (6.0이하 버전을 사용하다 업그레이드 한 경우 FCM==> FCM으로 변경하여야 기존 푸시키를 그대로 사용 할 수 있습니다.)
ANDROID_PNSID=FCM
WORK.THREAD.COUNT=10
##발송성공한 메세지 DB에 저장 여부.  권고: N, TIP: 발송성공로그파일은 저장되고 있음.
SUCCESS_SENTMSG_DB_INSERT=N
## 발송성공 및 수신/읽음확인 메시지 결과 처리 배치 크기
SENTMSG_BATCH_MAX_COUNT=1000
## 발송성공 및 수신/읽음확인 메시지 결과 처리 배치 주기(밀리초)
SENTMSG_BATCH_INTERVAL=1000
##레거시 시스템에서 대량 이벤트발생시 엄청남 개별 발송껀 처리 할 경우. 권고:Y
SYSTEM_SEND_YN=Y
##시스템 발송메세지 T_PUSH_MSG_REV_MASTER 테이블 저장 여부. 권고: N
SYSTEM_SENT_MASTERMSG_DB_INSERT=N
##시스템 발송통계정보(발송/실패/읽음확인) DB UPDATE 체크 주기(초)
SYSTEMSG_UPDATE_INTERVAL=60
##아래의 정책은 반드시 클라이언트(단말)가 로그인시 반드시 유저등록 API를 호출해 줄 때 가능하며 Y로 설정해 준다
POLICY_ONE_USER_ONE_DEVICE_YN=Y
## 1개의 CUID에 Android OS 1명, iOS OS 1명씩 등록하는 정책 (기본값: N)
## POLICY_ONE_USER_ONE_DEVICE_YN가 N일 때만 해당 옵션 사용 가능
POLICY_ONE_USER_PER_OS_YN=N
##원유저 원디바이스 일때 마지막 디바이스만 빼고 모두 삭제 처리. N일경우는 GUEST로 전환 시킴.
ONE_USER_ONE_DEVICE_ATHERDEVICE_DEL_YN=Y
## 원유저멀티디바이스정책==> 원유저원디바이스정책으로 변경시 아래를 Y로 셋팅
CHANGE_POLICY_FROM_MULTI_TO_ONE=N
## 정상적인 서버셧다운시 보내지 못한 메세지 저장 후 부팅시 계속발송 여부
SHUTDOWN_NOT_SEND_MSG_SAVE_YN=N
##서버장애 셧다운 자동저장기능. 발송속도 저하. 시스템 부하 증가
FORCE_KILL_LOG_USE_YN=N
FORCE_KILL_LOG_DIR=/kimhr/work/data/upmc/queueData/
##종류 : DAY, HOUR, MINUTE
FORCE_KILL_LOG_DATE_FORMAT=HOUR
FORCE_KILL_LOG_HISTORYSIZE=24
## UPNS MAX 유저할당
MAX_UPNS_ALLOCATE_USER=500000
## APNS 피드백서비스를 사용 할 경우 결과 정보를 REDIS에 저장할지 여부. Y로 설정하여 저장 했을 경우는 반드시 하루에 한번 이상 해당 결과를 요청하는 API를 호출해야 REDIS에 저장 데이타가 계속 증가하지 않는다.
APNS_FEEDBACK_REDIS_SAVE_YN=N
######################################################################################
# FCM 발송 및 에러처리
######################################################################################
FCM_ERROR_USER_REMOVE=Y
REMOVE_FILTER=Unregistered,NotRegistered
######################################################################################
# FCM 발송실패 (NotRegistered) 앱삭제시 UPNS서비스 가입 삭제 여부
######################################################################################
UPNS_REMOVE_YN=N
######################################################################################
# 핸드폰 단말이 아닌 STB 같은 도즈모드가 없는 기기 사용시 Y로 설정
######################################################################################
ONLY_UPNS_USE=N

##파일큐 사용여부(기본-메모리큐: N / 파일큐: Y)
FILEDB.USEYN=N
FILEDB.PATH=/kimhr/work/data/upmc/fileQueueData/

# 유라클 푸시제품에서 만든 테이블이 아닌곳에 수신확인/읽음확인 커스텀테이블 업데이트 쿼리사용. 해당 쿼리적용시 /WEB-INF/classes/sqlMap/사용DB/readCustomSql.xml에 쿼리 작성해야함.
REV_MSG_CUSTOM_TABLE_UPDATE_YN=N
REV_CUSTOM_TABLE_UP_QUERYS=customStatusRevUpdate,customStatusRevUpdate2
READ_CUSTOM_TABLE_UP_QUERYS=customStatusReadUpdate,customStatusReadUpdate2

## 유라클 UMS 사용시. 푸시 모니터링정보 UMS 모니터링 테이블에 넣어줄지 여부
UMS_MONITORING_YN=N

## Heartbeat 설정(PROVIDER 5.1.24+ 권장: 60 / 구버전 및 UMS 직접발송: 0) - PROVIDER와 값 일치 필수
STATUS_IDLE_TIME=0

######################################################################################
# 사이런트 푸시를 이용한 통계 설정
######################################################################################
# 삭제통계를 위해서는 해당 값을 Y/N으로 설정
SILENT_USER_METRIC_USE=N
# 하루에 한번 동작
# 04:00 분과 같이 HOUR:MINUTE 로 구분하여 입력
# HOUR는 0-23 입력 가능, MINUTE는 0-60 입력 가능
SILENT_USER_METRIC_START_TIME=04:00
SILENT_USER_METRIC_APP_ID=com.uracle.push.demo
SILENT_USER_METRIC_SERVICE_CODE=ALL
# 사일런트 푸시 발송한 이력을 발송 통계에 포함할것 인지 여부 Y/N으로 설정
SILENT_USER_METRIC_INCLUDE_SENTINFO=Y
