apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel 
  namespace: push 
spec:
  serviceName: sentinel 
  replicas: 3
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      securityContext:
        fsGroup: 999            
      containers:
        - name: sentinel 
          image: redis:7.4.6
          ports:
            - containerPort: 26379
          command:
            - sh
            - -c
            - |
              echo "Copying sentinel.conf to writable volume"
              cp /config/sentinel.conf /data/sentinel.conf

              echo "Waiting for Redis service DNS..."
              until getent hosts redis.push.svc.cluster.local; do sleep 1; done

              echo "Starting Sentinel"
              redis-sentinel /data/sentinel.conf

          volumeMounts:
            - name: sentinel-config
              mountPath: /config
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: sentinel-config
          configMap:
            name: redis-sentinel-config
        - name: data
          emptyDir: {}              
        
