architecture: replication

auth:
  enabled: true #Redis 접속 시 반드시 비밀번호(AUTH)가 필요함을 의미 
  password: morpheus+redis
  sentinel: false #Redis 노드 간 인증은 활성화되어 있으나, Sentinel 자체에 대한 인증(Sentinel 간 통신)은 비활성화 

replica:
  replicaCount: 3   # Master 1 + Slave 2 = Sentinel 3

sentinel:
  enabled: true
  quorum: 2

master:
  resources:
    requests:
      memory: 512Mi
      cpu: 300m
    limits:
      memory: 1Gi
      cpu: 1
