##\uBC18\uB4DC\uC2DC \uBAA8\uB450 \uC18C\uBB38\uC790\uB85C \uC785\uB825
APPID=test.world.sophy
#APNS_BUNDLEID_MAP=com.uracle.push.test:com.uracle.push.test.voip,com.uracle.push.demo:com.uracle.push.demo.ios
## FCM PROTOCOL KIND : HTTP
FCM_USE_PROTOCOL=HTTP

## APNS PROTOCOL KIND : HTTP2
APNS_USE_PROTOCOL=HTTP2
## APNS HTTP PROTOCOL PORT : DEFAULT or ALTERNATE
APNS_HTTP2_PORT=DEFAULT
## binary=>http2\uB85C \uBCC0\uACBD\uB418\uB294 \uC0AC\uC774\uD2B8 \uC911 alert\uB97C String\uC73C\uB85C \uB9CC \uCC98\uB9AC \uAC00\uB2A5\uD558\uB3C4\uB85D \uD074\uB77C\uC774\uC5B8\uD2B8\uAC00 \uAC1C\uBC1C\uB41C \uACBD\uC6B0. STRING\uB85C \uC14B\uD305
APNS_ALERT_KIND=OBJECT

##\uD574\uB2F9\uC0AC\uD56D\uC774 \uC5C6\uC73C\uBA74 \uBE48\uAC12\uC73C\uB85C \uB123\uC5B4\uB454\uB2E4. ex) FCM_APIKEY1=
FCM_TOKEN_SRC1=./conf/mock-project-id-none.json
#FCM_TOKEN_SRC2=./conf/mock-project-id-none.json

### FCM \uBA54\uC138\uC9C0 alert, ext \uC815\uBCF4 \uC554\uD638\uD654 \uC5EC\uBD80. \uC554\uD638\uD654 \uCC98\uB9AC\uD560 appid\uB97C \uC27C\uD45C \uAD6C\uBD84\uC790\uB85C \uB123\uC5B4\uC8FC\uC138\uC694.
#FCM_MSG_ENCRYPT_APP_LIST=com.uracle.push.test
###APNS HTTP2 AuthKey \uBC29\uC2DD \uC77C \uACBD\uC6B0 \uC815\uBCF4
APNS_HTTP2_TOKEN_SRC1=./conf/token-auth-private-key.p8
APNS_HTTP2_TEAMKEY1=TEAMKEY123
APNS_HTTP2_KEYID1=KEYID12345

##APNS MOD ex)DEV, REAL
#APNS_MODE1=DEV
#APNS_DEV_CERT_SRC1=./conf/single-topic-client_dev.p12
#APNS_DEV_CERT_PASSWD1=qwer1234
#APNS_DEV_CERT_EXPIRE1=2025-12-31
#APNS_REAL_CERT_SRC1=./conf/single-topic-client_real.p12
#APNS_REAL_CERT_PASSWD1=qwer1234
#APNS_REAL_CERT_EXPIRE1=2025-12-31

WPNS_APPLICATION_SERVER_PUBLIC_KEY=BGBHt90FWmtQxqDmfG8yfLLvZ1iq3xOsG8lWjA5ckoD8F-hyvLrni4YLWxwWPkihFtLUkGqOx0kEgk9dUKt3NGA
WPNS_APPLICATION_SERVER_PRIVATE_KEY=rJV7IltIRuGnf89Pydl6NMDYYKVdUQeH8zeCI62bzxA

################################################
# \uBCC0\uACBD\uC2DC\uB294 \uB0B4\uC6A9\uC744 \uD655\uC2E4\uD788 \uC54C\uACE0 \uBCC0\uACBD\uD558\uC138\uC694.
################################################
PORT=10420
SSLPORT=18443
MONITORING_PORT=10421
#PORT=10420
#SSLPORT=18443
#MONITORING_PORT=10421
WORKTHREAD_CNT=50
## EXT JsonObject \uC0AC\uC6A9\uC5EC\uBD80. 5.1.0-R6 \uC774\uC804 \uAC1C\uBC1C\uB41C \uC571\uC77C \uACBD\uC6B0 N \uB85C \uC14B\uD305\uD574\uC57C\uD568.
EXT_JSONOBJECT_USE_YN=N
##APNS \uBA54\uC138\uC9C0 \uB370\uC774\uD0C0 EXT \uAC12 \uC124\uC815
APNS_USE_EXT=Y
## \uC571\uC544\uC774\uB514 \uB118\uAE30\uC9C0 \uC54A\uC74C
APNS_REMOVE_APPID=Y
## APNS HTTP2 \uC0AC\uC6A9 \uC2DC \uBA54\uC2DC\uC9C0\uB9CC \uC785\uB825\uD558\uBA74 \uB0B4\uC6A9\uC744 JSON \uD615\uD0DC\uB85C \uAC00\uACF5\uD558\uC9C0 \uC54A\uACE0 \uADF8\uB300\uB85C \uBCF4\uB0B4\uAE30.
APNS_PREFER_STRING_REPRESENTATION=N
## EXT \uB370\uC774\uD0C0\uB97C \uC7AC\uAC00\uACF5 \uD558\uC9C0 \uC54A\uACE0 \uBC1B\uC740 \uADF8\uB300\uB85C \uBCF4\uB0B4\uAE30.
APNS_EXT_ORG_SEND=Y
## \uC0AC\uC6A9\uC790 \uBBF8 \uC811\uC18D\uC2DC \uBCF4\uAD00\uC77C
FCM_OFFLINE_SAVE_DAY=28
## \uBC1C\uC1A1\uC2DC\uAC04 \uC81C\uD55C
SEND_TIME_OVER_YN=N
NOT_SEND_TIME_LIST=1,2,3,4,5,6
## FCM \uBC1C\uC1A1 \uD0C0\uC784\uC544\uC6C3(\uAE30\uBCF8\uAC12 200 / \uB2E8\uC704 ms)
FCM_SEND_TIMEOUT=200
## FCM \uBC1C\uC1A1 \uD480 \uD06C\uAE30(\uAE30\uBCF8\uAC12 70 / \uB2E8\uC704 \uAC1C\uC218)
FCM_SEND_POOL_SIZE=70
## FCM HTTP KeepAlive \uC720\uC9C0\uC2DC\uAC04(\uAE30\uBCF8\uAC12 3 / \uB2E8\uC704 \uBD84)
FCM_SEND_KEEPALIVE_TTL=3
## FCM HTTP \uC811\uC18D \uC720\uC9C0\uC2DC\uAC04(\uAE30\uBCF8\uAC12 10 / \uB2E8\uC704 \uBD84)
FCM_SEND_CONNECTION_TTL=10

## FCM HTTP \uBC1C\uC1A1 \uC4F0\uB808\uB4DC \uC218(\uAE30\uBCF8\uAC12 50 / \uB2E8\uC704 \uAC1C\uC218)
FCM_SEND_THREAD_CNT=50
##\uC0AC\uC6A9\uC790 \uC815\uC758 FCM/APNS \uBC1C\uC1A1\uB300\uAE30\uD050 \uB9CC\uB8CC\uC2DC\uAC04 \uC0AC\uC6A9\uC5EC\uBD80.
MENUAL_SEND_EXPIRE=Y
## (\uD14C\uC2A4\uD2B8 \uBAA8\uB4DC) \uD2B9\uC815 APPID\uB294 FCM, APNS \uC11C\uBC84\uB85C \uBA54\uC2DC\uC9C0\uB97C \uC804\uB2EC\uD558\uC9C0 \uC54A\uACE0, \uBB34\uC870\uAC74 \uC131\uACF5 \uCC98\uB9AC
TEST_APPID=com.upns.push.test

##\uD30C\uC77C\uD050 \uC0AC\uC6A9\uC5EC\uBD80(\uAE30\uBCF8-\uBA54\uBAA8\uB9AC\uD050: N / \uD30C\uC77C\uD050: Y)
FILEDB.USEYN=N
FILEDB.PATH=./data/fileQueueData/
# (\uD30C\uC77C\uD050 \uC804\uC6A9) \uBC1C\uC1A1 \uD050\uC758 \uBD84\uBC30 \uBC29\uC2DD(\uAE30\uBCF8: N / Hash \uBC29\uC2DD: Y)
QUEUE.HASH.ALGO=N
# \uD30C\uC77C\uD050\uC5D0 \uC800\uC7A5\uB41C \uBC1C\uC1A1\uB418\uC9C0 \uBABB\uD55C \uBA54\uC138\uC9C0 \uB9CC\uB8CC\uC2DC\uAC04.
NOTSEND_ELAPSEDTIME=6
################################################
# N/W \uAD00\uB828 \uC7A5\uC560\uC2DC Queue\uC5D0 \uC801\uC7AC\uB9CC \uB418\uACE0, WorkerThread\uAC00 WATING \uC0C1\uD0DC\uAC00 \uB420 \uB54C \uC790\uB3D9 \uC7A5\uC560\uC870\uCE58 \uAE30\uB2A5
# Queue > 0 && OUT == 0 \uC870\uAC74\uC5D0\uC11C MALFUNCTION_WARN_TIME \uC124\uC815 \uAC12 \uCD08\uACFC\uC2DC \uD504\uB85C\uBC14\uC774\uB354 \uC11C\uBE44\uC2A4\uB97C \uC81C\uC5B4\uD560 \uC218 \uC788\uC74C
################################################
## \uC790\uB3D9 \uC7A5\uC560\uC870\uCE58 \uC0AC\uC6A9\uC720\uBB34(\uC0AC\uC6A9\uC2DC \uD050 \uBAA8\uB2C8\uD130\uB9C1 \uC815\uBCF4 \uC218\uC9D1 http://SERVER_IP:10421/getIdleInfo.prv)
MALFUNCTION_USE_YN=N
## Queue > 0 && OUT == 0 \uC870\uAC74\uC744 \uB9CC\uC871\uD558\uB294 \uD69F\uC218(\uBD84 \uB2E8\uC704, \uCD5C\uC18C 3, \uAD8C\uC7A5 5 \uC774\uC0C1)
MALFUNCTION_WARN_TIME=5
## \uC7A5\uC560\uC870\uCE58 \uC120\uD0DD NONE or UNBIND or KILL or RESTART
##   NONE   : (\uAE30\uBCF8\uAC12) \uC544\uBB34\uB7F0 \uC5D1\uC158\uC744 \uD558\uC9C0 \uC54A\uC74C
##   UNBIND : \uC11C\uBE44\uC2A4 \uD3EC\uD2B8(10420)\uB97C \uC815\uC0C1 \uBC1C\uC1A1\uC774 \uB420 \uB54C\uAE4C\uC9C0 Unbind
##   KILL   : PROVIDER \uC885\uB8CC(\uC218\uB3D9\uC73C\uB85C \uAE30\uB3D9\uC774 \uD544\uC694\uD568)
##   RESTART: \uBAA8\uB4E0 \uC11C\uBE44\uC2A4 \uD3EC\uD2B8\uB97C Unbind -> \uC2E0\uADDC PROVIDER \uAE30\uB3D9 -> \uD604\uC7AC PROVIDER \uC885\uB8CC
MALFUNCTION_BYPASS_ACTION=NONE
## MALFUNCTION_BYPASS_ACTION\uC744 RESTART \uC124\uC815\uC2DC \uAE30\uB3D9\uD560 \uC258 \uC2A4\uD06C\uB9BD\uD2B8(\uAC12\uC5D0 \uACF5\uBC31\uC774 \uC5C6\uC5B4\uC57C \uD568)
MALFUNCTION_RESTART_CMD=/bin/bash /Users/swryu/IdeaProjects/uracle/push-5.1/provider/start.sh

APNS_MSG_EXPIRE_SECOND=86400
################################################
# provider \uC778\uC99D\uC11C \uC5C5\uB85C\uB4DC \uC5F0\uACB0 \uD5C8\uC6A9 \uC544\uC774\uD53C.
################################################
security.using=false
security.ignore.targetCount=4
security.ignore.targets.ip1=127.0.0.1
security.ignore.targets.ip2=0:0:0:0:0:0:0:1
security.ignore.targets.ip3=0:0:0:0:0:0:0:1%0
security.ignore.targets.ip4=100.100.100.11-20

## \uC720\uB77C\uD074 UMS \uC0AC\uC6A9\uC2DC. \uD478\uC2DC \uBAA8\uB2C8\uD130\uB9C1\uC815\uBCF4 UMS \uBAA8\uB2C8\uD130\uB9C1 \uD14C\uC774\uBE14\uC5D0 \uB123\uC5B4\uC904\uC9C0 \uC5EC\uBD80
UMS_MONITORING_YN=N

## Heartbeat \uC124\uC815(UPMC 5.1.42+ \uAD8C\uC7A5: 60 / \uAD6C\uBC84\uC804 \uBC0F UMS \uC9C1\uC811\uBC1C\uC1A1: 0) - UPMC\uC640 \uAC12 \uC77C\uCE58 \uD544\uC218
STATUS_IDLE_TIME=0
