apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: push 
data:
  sentinel.conf: |
    port 26379
    dir /data
    protected-mode no

    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes

    sentinel monitor mymaster redis.push.svc.cluster.local 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 10000
    sentinel parallel-syncs mymaster 1
    sentinel auth-pass mymaster morpheus+redis    
